@URL = http://localhost:3000
@contentType = application/json

###

POST {{URL}}/employee HTTP/1.1
content-type: {{contentType}}

{
    "firstName": "Windom",
    "lastName": "Earl",
    "hireDate": null,
    "phone": null,
    "address": null,
    "avatarUrl": null
}

###

POST {{URL}}/employee HTTP/1.1
content-type: {{contentType}}

{
    "firstName": "Windom",
    "lastName": "Earl",
    "EXTRA": "SHOULD FAIL"
}

###

POST {{URL}}/employee HTTP/1.1
content-type: {{contentType}}

{
    "firstName": "Windom",
    "lastNameMissing!": "Earl Fails"
}


###

POST {{URL}}/employee/togglestatus HTTP/1.1
content-type: {{contentType}}

{
    "id": 1,
    "active": 1
}

###

POST {{URL}}/employee/togglestatus HTTP/1.1
content-type: {{contentType}}

{
    "id": 1,
    "active": 0
}

###

PUT {{URL}}/employee HTTP/1.1
content-type: {{contentType}}

{
    "id": 3,
    "firstName": "Dale",
    "lastName": "Cooper",
    "hireDate": "2020-01-01 11:30:00",
    "phone": null,
    "address": null,
    "avatarUrl": null
}


###

DELETE {{URL}}/employee HTTP/1.1
content-type: {{contentType}}

{
    "id": 2
}
